---
apiVersion: v1
kind: Pod
metadata: 
    name: demopod1
    labels: 
      app: dev
spec:
  containers:
    - name: demo1
      image: httpd
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
