# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
# pods "elephant" was not valid:
# * spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations)
#   core.PodSpec{
#   	Volumes:        {{Name: "default-token-hcskr", VolumeSource: {Secret: &{SecretName: "default-token-hcskr", DefaultMode: &420}}}},
#   	InitContainers: nil,
#   	Containers: []core.Container{
#   		{
#   			... // 6 identical fields
#   			EnvFrom: nil,
#   			Env:     nil,
#   			Resources: core.ResourceRequirements{
# - 				Limits: core.ResourceList{
# - 					s"memory": {i: resource.int64Amount{value: 20971520}, s: "20Mi", Format: "BinarySI"},
# - 				},
# + 				Limits: core.ResourceList{
# + 					s"memory": {i: resource.int64Amount{value: 10485760}, s: "10Mi", Format: "BinarySI"},
# + 				},
#   				Requests: {s"memory": {i: {...}, s: "5Mi", Format: "BinarySI"}},
#   			},
#   			VolumeMounts:  {{Name: "default-token-hcskr", ReadOnly: true, MountPath: "/var/run/secrets/kubernetes.io/serviceaccount"}},
#   			VolumeDevices: nil,
#   			... // 11 identical fields
#   		},
#   	},
#   	EphemeralContainers: nil,
#   	RestartPolicy:       "Always",
#   	... // 25 identical fields
#   }

#
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-04-20T08:56:20Z"
  name: elephant
  namespace: default
  resourceVersion: "1882"
  uid: c9d7d813-1ff3-4a2d-bb02-c74beee6fc58
spec:
  containers:
  - args:
    - --vm
    - "1"
    - --vm-bytes
    - 15M
    - --vm-hang
    - "1"
    command:
    - stress
    image: polinux/stress
    imagePullPolicy: Always
    name: mem-stress
    resources:
      limits:
        memory: 20Mi
      requests:
        memory: 5Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-hcskr
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: controlplane
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-hcskr
    secret:
      defaultMode: 420
      secretName: default-token-hcskr
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-04-20T08:56:20Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-04-20T08:56:20Z"
    message: 'containers with unready status: [mem-stress]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-04-20T08:56:20Z"
    message: 'containers with unready status: [mem-stress]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-04-20T08:56:20Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://df19f06b0f7b671b67d557101dcc1c696d1fc7d0ecb5e3e20eface42acd2e787
    image: polinux/stress:latest
    imageID: docker-pullable://polinux/stress@sha256:b6144f84f9c15dac80deb48d3a646b55c7043ab1d83ea0a697c09097aaad21aa
    lastState:
      terminated:
        containerID: docker://df19f06b0f7b671b67d557101dcc1c696d1fc7d0ecb5e3e20eface42acd2e787
        exitCode: 1
        finishedAt: "2021-04-20T08:57:17Z"
        reason: OOMKilled
        startedAt: "2021-04-20T08:57:17Z"
    name: mem-stress
    ready: false
    restartCount: 3
    started: false
    state:
      waiting:
        message: back-off 40s restarting failed container=mem-stress pod=elephant_default(c9d7d813-1ff3-4a2d-bb02-c74beee6fc58)
        reason: CrashLoopBackOff
  hostIP: 10.236.17.9
  phase: Running
  podIP: 10.244.0.5
  podIPs:
  - ip: 10.244.0.5
  qosClass: Burstable
  startTime: "2021-04-20T08:56:20Z"
