---
apiVersion: apps/v1
kind: Deployment
metadata:
      name: red
      labels:
         name: red
spec:
      replicas: 2
      selector:
         matchLabels:
             name: red
      template:
         metadata:
             name: red
             labels:
               name: red
         spec:
            containers:
               - image: nginx
                 name: nginx
            affinity:
              nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                     nodeSelectorTerms:
                      - matchExpressions:
                              - key: node-role.kubernetes.io/master 
                                operator: Exists
